[package]
name = "rust-svn"
version = "0.1.0"
authors = ["Bernd-L <18219148+Bernd-L@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
